Repository CMU-313/fall-2021-hw2-connect5, pull requests merged in 2021-09, with the labels that each got.

#19 Zixu HW1 Fix: fix Lighthouse "Links do not have a discernible name" warning
  mayan/apps/appearance/templates/appearance/menu_main.html
Labels: enhancement

#21 add button to documents page that links to a review view
  mayan/apps/documents/apps.py
  mayan/apps/documents/icons.py
  mayan/apps/documents/links/document_links.py
  mayan/apps/documents/urls.py
  mayan/apps/documents/views/document_views.py
Labels: enhancement

#24 Add review form and metric form
  mayan/apps/documents/forms/metric_forms.py
  mayan/apps/documents/forms/review_forms.py
  mayan/apps/documents/models/__init__.py
  mayan/apps/documents/models/applicant.py
  mayan/apps/documents/models/metric.py
  mayan/apps/documents/models/reviewer.py
  mayan/apps/documents/models/reviewer_assignment.py
  mayan/apps/documents/permissions.py
  mayan/apps/documents/urls.py
  mayan/apps/documents/views/document_views.py
  mayan/apps/documents/views/metric_views.py
Labels: enhancement

#33 Albert HW1 Fix - Add discernible name to notification & message icon link in the top navigation bar
  mayan/apps/events/links.py
  mayan/apps/messaging/links.py
Labels: enhancement

#38 set jsonschema version to 3.2 to make tests work
  requirements/testing-base.txt
Labels: bug

#39 Add manual testing for review page
  README.md
  TESTING.md
Labels: testing
